### ISSUE TITLE
Consider using BitTorrent v2-like protocol for image content transfer?

### ISSUE THREAD

**Issue by infogulch** [containers/composefs#113]
Hi! I noticed that one of the nice features of composefs, the ability to store and share content at a file-level, aligns with a similar feature found in the BitTorrent v2 protocol.

> This allows sharing of content files between images, even if the metadata (like the timestamps or file ownership) vary between images.
> 
> &mdash; <cite>https://github.com/containers/composefs#usecase-container-images</cite>

> The fact that each file has its own hash tree, and that its leaves are defined to be 16 kiB, means that files with identical content will always have the same merkle root. This enables finding matches of the same file across different torrents.
> 
> &mdash; <cite>http://libtorrent.org/features-ref.html#bittorrent-v2</cite>

From what I've seen, composefs' current/proposed image transfer protocol is roughly one http request per file from a dedicated host. I suspect a P2P-based image downloading system would achieve greater total throughput, lower latency, and better resilience for many installations.

The basic idea would be to make something similar to [uber/kraken](https://github.com/uber/kraken) or [dragonfly](https://github.com/dragonflyoss/Dragonfly2), both p2p-based docker image transfer registries, but for composefs images.

Has something like this been considered before?

**Comment by alexlarsson** [comment]
Composefs is not meant to be an entire infrastructure for image handling, it is just a mechanism for the mount of an image. So, it will not have any kind of image transfer protocol on its own. Instead the goal is to use it from other things, in partcular for ostree and OCI container images. These already have existing transport mechanisms that will be used.

Of course, other users of composfs may use whatever other mechanisms they want, including bittorrent. However, that would be outside of the scope of composefs itself.
