### ISSUE TITLE
consider adding ima as alternative

### ISSUE THREAD

**Issue by cgwalters** [containers/composefs#171]
So...basically today for RHEL9 we use XFS by default, which doesn't yet support fs-verity.

One thing I could imagine doing is basically adding support for IMA in all the places we support fs-verity - on the cfs image, and the backing store.

I *think* because of how IMA works we might not even need the `verity=require` flow that was needed for overlayfs+fs-verity.

This is a half baked thought.  I don't know if it's worth it.

**Comment by alexlarsson** [comment]
I'm not sure how this would work. Like, where would the `security.ima` xattr be stored? 

For example, I can imagine the CAS having `security.ima` set on all files, and some IMA policy set such that all files on that filesystem mount require a digest. However, you could still replace a file in the CAS (as long as you set a new ima digest on it) becase the digest is not in the composefs image.

So, the second approach is to have the metacopy file in the erofs image have the xattr. However, the kernel will expect that to have the digest of the file on the erofs image (which is empty), not the digest of the file in the CAS, so this won't work.

The only thing I can see that would work is if you changed overlayfs to also be able to validate an IMA digest for a file at open time. However, this is quite an addition to overlayfs.

Additionally, IMA digests (except when using fs-verity with IMA) are not lazily computed, which will make file open quite slow as it has to compute the digest of the entire file.
