### ISSUE TITLE
support for reading .cfs images

### ISSUE THREAD

**Issue by jluebbe** [containers/composefs#182]
For some use-cases, it would be useful to have an API to recreate an `lcfs_node` tree from `.cfs` image:

- fetching objects needed by an image from a remote object store
- removing unused objects from a local, shared object store given a set of `.cfs` images
- listing missing objects given a `.cfs` image

My main motivation for this would be RAUC's [artifact updates](https://github.com/rauc/rauc/issues/969), where we could use this to stream missing objects from the remote update bundle.

**Comment by alexlarsson** [comment]
In main now
