### ISSUE TITLE
portability issues found while packaging

### ISSUE THREAD

**Issue by Kiskae** [containers/composefs#200]
While preparing packaging for 0.9.0 over at https://github.com/NixOS/nixpkgs/pull/256892 I ran into a few potential portability issues while trying various cross-compilations and thought to report them.

- `#import <endian.h>` in `libcomposefs/lcfs-fsverity.c` - [not supported by darwin or freebsd](https://stackoverflow.com/a/58418801/1452094)
- `#import <error.h>` in `tools/*` - [gnu extension, not available when using musl](https://wiki.gentoo.org/wiki/Musl_porting_notes#error.h:_No_such_file_or_directory)
- `os.setxattr` in `tests/gendir` - throws an exception if the file system the builder is running on does not support xattrs:
```
composefs> Traceback (most recent call last):
composefs>   File "/build/source/tests/./gendir", line 193, in <module>
composefs>     make_dir(root, dirs)
composefs>   File "/build/source/tests/./gendir", line 163, in make_dir
composefs>     set_user_xattr(path)
composefs>   File "/build/source/tests/./gendir", line 104, in set_user_xattr
composefs>     os.setxattr(path, name, value, follow_symlinks=False)
composefs> OSError: [Errno 95] Operation not supported: b'/build/lcfs-test.pTv96t/root'
```

While the file system itself only works on linux, it would be nice if the tooling to create or inspect a composefs image works on other unix variants.

**Comment by Kiskae** [comment]
Not a portability issue, but `descriptor.data_size_be = htole64(ctx->file_size);` indicates that should probably be `data_size_le` to avoid confusion.

**Comment by alexlarsson** [comment]
Lemme have a quick look at this before finalizing the 0.9.0 release

**Comment by alexlarsson** [comment]
@Kiskae Btw, is there any interest in using composefs for the nix store? Seems like it could make a good match?

**Comment by Kiskae** [comment]
I'm not involved with the nix implementation so I wouldnt be able to tell you if there is interest on that side.

Regarding the use of composefs for the nix store I'm not sure if it would work for the global store since it changes fairly frequently (every time someone realizes a derivation), but there might be a use in the sandboxed builders to create a local version of the nix store without exposing all the build dependencies on the global store.

**Comment by alexlarsson** [comment]
I meant more for the local store to do e.g. deduplication, similar to the hardlink optimization that nix does, but more powerful.

**Comment by Kiskae** [comment]
With global store I meant the nix store at /nix/store, which I presume you meant with local store.

I thought that the only way to update an active composefs image would be to regenerate the erofs file and remount the image. Since this would need to happen each time something is realized for use outside of the nix daemon I assumed it would make composefs less attractive.

Regardless there has been a push recently for making parts of the nix store more content-addressible, so I'm sure someone will look into it in the future.

**Comment by alexlarsson** [comment]
I gotta say I don't know the nix store layout all that well, but it *seems* near enough that you could imagine a global shared content addressed store and then a composefs image per package. Might not work though.

**Comment by Kiskae** [comment]
Found another issue that was hiding behind the fact that `libyajl` does not build statically so the `composefs-from-json` tool didn't get tested.

When built with dynamically linked musl the `composefs-from-json` tool breaks because [musl uses readv/writev for stdio](https://wiki.musl-libc.org/functional-differences-from-glibc.html). Since the seccomp filter does not allow these syscalls the tool fails silently since it can't write to stdout or stderr.

```console
readv(0, [{iov_base=0x7f7f9ca8e560, iov_len=1023}, {iov_base=0x7f7f9cb53328, iov_len=1024}], 2) = -1 ENOSYS (Function not implemented)
writev(2, [{iov_base="composefs-from-json: ", iov_len=21}, {iov_base=NULL, iov_len=0}], 2) = -1 ENOSYS (Function not implemented)
writev(2, [{iov_base="parse_file", iov_len=10}, {iov_base=NULL, iov_len=0}], 2) = -1 ENOSYS (Function not implemented)
writev(2, [{iov_base="", iov_len=0}, {iov_base=": ", iov_len=2}], 2) = -1 ENOSYS (Function not implemented)
writev(2, [{iov_base="", iov_len=0}, {iov_base="Function not implemented", iov_len=24}], 2) = -1 ENOSYS (Function not implemented)
writev(2, [{iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 2) = -1 ENOSYS (Function not implemented)
```

It does work if you try `--help` since the seccomp filter only gets installed when it processes a file.

**Comment by alexlarsson** [comment]
Filed as https://github.com/containers/composefs/issues/204

**Comment by alexlarsson** [comment]
@Kiskae Also, can you file a separate issue for the musl seccomp issue?
