### ISSUE TITLE
mkcomposefs: objects not being created

### ISSUE THREAD

**Issue by ldts** [containers/composefs#257]
I believe there is a regression (snippet below) which prevents the objects from being created when providing the --digest-store path.

![image](https://github.com/containers/composefs/assets/10456021/a367bbfa-d96f-4bf8-9ead-bb142fa7d612)

updating the highlighted line to the opposite condition (!=) works around the issue.

**Comment by ldts** [comment]
btw I didnt send a patch because I am being asked by legal to not share code at this early stage while we evaluate the project (I know what a patch is and how to collaborate...I just noticed this while testing so I thought I'd comment on it )

**Comment by alexlarsson** [comment]
No, it is because small files are inlined these days: https://github.com/containers/composefs/commit/b99a9781b337a44666b8c579b5f572fe5971ab0e

**Comment by alexlarsson** [comment]
This is making some old demos and tutorial not work anymore though, and we should probably go back and change them to minimize confusion.

**Comment by ldts** [comment]
> No, it is because small files are inlined these days: [b99a978](https://github.com/containers/composefs/commit/b99a9781b337a44666b8c579b5f572fe5971ab0e)

ah ok, thanks @alexlarsson
