### ISSUE TITLE
dropping autotools build

### ISSUE THREAD

**Issue by cgwalters** [containers/composefs#301]
Since https://github.com/containers/composefs/pull/300 we now have a meson build. I don't know of a strong reason to keep the autotools one around.

This issue tracks the goal of removing it; if you have objections or concerns, please cite them here.

**Comment by alexlarsson** [comment]
The one thing our meson code doesn't do is generate the .spec from spec.in during dist.
It can be done, like so: https://gitlab.com/CentOS/automotive/src/autoinit/-/commit/2d1bbad976e3729faf864c205dd830cd04d7aa68

Otoh, maybe its time to drop the specfile from the tarball instead?
