### ISSUE TITLE
Testing the file `should-fail-self-hardlink.dump` fails with `mkcomposefs: Invalid embedded NUL character at position 22` 

### ISSUE THREAD

**Issue by eriksjolund** [containers/composefs#373]
I tried e2afe90d4e58b495b7a5b4a7d3e5d2c92a2d61c8

```
# mkcomposefs --from-file composefs/tests/assets/should-fail-self-hardlink.dump resultfile
mkcomposefs: Invalid embedded NUL character at position 22
```

I had expected to see some error message starting with  `mkcomposefs: Self-referential hardlink`
because of the filename _should-fail-self-hardlink.dump_

**Comment by cgwalters** [comment]
Thanks for trying this out! Fix in https://github.com/containers/composefs/pull/374

However, what would clearly be better here is to enhance the test suite to have a notion of "expected error"...which would be nicer to do if we supported comments in dumpfiles (maybe with an opt-in for new syntax) and then our test suite could embed the expected error like:
```
# expect: Self-referential hardlink
/ 4096 40555 2 0 0 0 0.0 - - - 
/037blockdev 0 @63340777 2 0 0 0 0.0 /037blockdev - -
```

or so.
