### ISSUE TITLE
Add way to find backing store for data

### ISSUE THREAD

**Issue by alexlarsson** [containers/composefs#56]
As mentioned here: https://github.com/ostreedev/ostree/pull/2640#issuecomment-1171334545
ignition would like to be able to track which block devices as used by a mount. We can't currently always do this. For example, the mount source is a relative pathname.  We should maybe make this an absolute pathname?

There might be similar issues with the basedir.

**Comment by alexlarsson** [comment]
We do expose all the backing paths in the mount info, although they are relative if they were supplied relative. I looked at other stuff, and nothing in the current kernel seems to change given options to absolute paths when printed. Maybe we just need to be careful about passing important mount options by full paths when we mount stuff.

**Comment by cgwalters** [comment]
I think this is not necessary; in general, we just need to teach tooling to look at the underlying physical root filesystem, which is done in https://github.com/coreos/coreos-installer/pull/1203
