### ISSUE TITLE
incorrect length parameter given to strncat in mkcomposefs.c

### ISSUE THREAD

**Issue by eriksjolund** [containers/composefs#81]
In the file _tools/mkcomposefs.c_, incorrect length parameters are given to strncat(), see for instance

```
	strncpy(tmppath, dst_base, sizeof(tmppath) - 1);
	strncat(tmppath, "/.tmpXXXXXX", sizeof(tmppath) - 1);
```

**Comment by flouthoc** [comment]
I think it length parameters should be of `src` i.e (`dst_base` and `/.tmpXXXXXX`) here instead of buffer i.e `tmppath`.

**Comment by eriksjolund** [comment]
I tried running __mkcomposefs__ with a long path:

```
$ str=$(python3 -c "print(200*'A')");
$ echo $str | wc -c
201
$ for i in {1..23}; do mkdir $str; cd $str; done ; cd
$ mkcomposefs --absolute $str outfile
Segmentation fault (core dumped)
```

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/composefs/pull/84
